apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo-ace
data:
  branch: ocp47-2021-2
  host: github.com
  org: Telstra-mq-hub
  owner: Telstra-mq-hub
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/Telstra-mq-hub/multi-tenancy-gitops-apps.git
