apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCd13hg11HrLPNqk5f7VX9JxQ8Dkn0n4HvhCgE57ALUx466x5VvK5QmphMqWtLUd8sydyTs8VRHuAnT0O/JFvXTHLblBvRQtKcll7ciMr6gyYV+F4pwEqRhIa7Ciwt28fXUkxlutBTlUbJ/s0FmKvPFeQTYqT435PXIwONXhO/wEu8DvVYWRdmThc+PTBVi6ix76ilIGJqijcWKe0pX5Fd+mEVkqr9QOr3c2Kx0Qz+dnt4WFYYB7qbB1q6x1rtuZSVrXAVzHImA5eCjTGdEWxYsSEay5wHrvNxHEVJpSI8rhtxBFe4rCOerg3aVcAmHFIT4MYR+4nkfGWYF4BMai/Wp7tpz4qRtPtskIUzTkwHW9diCqkWk8BkvkEudqughtDnqaHQxYL0JTaKTqvQFHu85B44lPImJclGZfN5x5h3IHAlGS4B4uqFI/OFEmJHr19Yi3RX4UVIxo8kRPDz7hZAyuMqO87Jc0gb7cXFQbC0LRqa9NilwaudL6rdiRKtZycHOJOySLdfp1sFUBZmowEp5kB+ARAiqz+QiAuQIH8J96VAzbKBd4KoCpPIsFw78vXz7fyYfvrtrF3D5L9IkH9sa8RJuTp+XfXhWj+XcKGOZWPw1mdabV3Q2+HZfSLWgCOyqj/ChQZMg1yvrqNKbUGVDqTprLmzZ2WFFHPm4lD07iG9386TzqxigJoIhPfjmzSPGYUOnL2aLr/xr8nApngYZSUKB5ztbwHkTd4fUA/UGWrRadSNVHlvH6DwI0QqkoeyApcUq2gvmaFHCnMXYrAMuWCcXPOxpSTzYyJG84PZgGeTeu58xb5FXihzLc+7Dy+6G2xWhY0W9U9KBDAJboVuACrCJxCceySm3XsAiGjWtYbAnwqXYv6NcpLP5a00CKHKXMQ8iW32K509TLXxUw2iih3mBPczrRKhhwvqHvYn1rUC3moBh9OjtynzY5DDCzKA=
    IBM_ENTITLED_REGISTRY_USER: AgA5gwPBsYSQ+ue9cAXZwULew4TIniUDj/yE+QoDtl1r6QeKq6rBAB0mVWwiWBGqCzXeyUMf/8FYKlDXCIAV+FFvNFVDu01Hj8tyTB3tmYycbO09x5RxOB3L5pG1JdA4E7A7czWrA+R3vflBGBvs0HasF0RPvcXBIoSx9jl1m8acHLKNsXszix/5Z2+6R2jpxcWyk6V5XXChWs6vEZJqAhuTGC3hCxlMmkCyAGDCEZ06YfRpZrohnx3bmU/6O4UbytCW6Dxjp57JwjSIvU3mXpAeBA0IBAycU8R72ya4asg3z5Mag9iWcXiM2Vu9BeR7uTSouGolXWMb1BvCFYWXlJxYqW/9oratbpGYO0u9OOMzBXgdiA93+nsQBBX3Yiy7mozHqvWh1S56cXhNqNwJWiIGb6JJZhrLxCtmht25HeN0fPjM2QvGjI5d+bcnxiSMJDEBJOj2W35zgmGfEXhSaS9Y4RyCMgBglmfUbZflUxRRGesv7rE1KRHu5M2gveFmXZdqmGzrzPp1SdB3wcrfaOrS3p52n628hBrHHOs7PK1mjU8Yff7XTEE5kZdysXSmXx0/ALUzb3bAuMEPl9W+S9ePlYCveboJ4Bk6RJaALPvBYYnivCC4eRdBFkzgR2jOP3LWqY8wHJeYZYYY+n2W2/9l6H9XYvRDdKfRihgVFOQaNbURfEqs+Vsa18hdTAUV09x5Fg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

